project:
  type: website
  output-dir: docs

website:
  title: " "
  navbar:
    right:
      - href: contents/eng/english_index.qmd
        text: Home page (english)
      - about.qmd
    left:
      - href: index.qmd
        text: Pagina iniziale (italiano)

format:
  html:
    css: styles.css
    theme: lux
    
    
  

editor: visual

