project:
  type: website

website:
  title: "Laboratorio di elettroencefalografia: guida"
  navbar:
    left:
      - href: contents/eng/english_index.qmd
        text: English version
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc_float: true

editor: visual

